#!/bin/sh
### BEGIN INIT INFO
# Provides:          tailscaled
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tailscale VPN daemon
### END INIT INFO

DAEMON=/usr/sbin/tailscaled
PIDFILE=/var/run/tailscaled.pid

case "$1" in
  start)
    echo "Starting tailscaled..."
    start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- --state=/var/lib/tailscale/tailscaled.state --tun=userspace-networking
    ;;
  stop)
    echo "Stopping tailscaled..."
    start-stop-daemon --stop --pidfile $PIDFILE
    rm -f $PIDFILE
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  status)
    if [ -f $PIDFILE ]; then
      echo "tailscaled is running (PID $(cat $PIDFILE))"
    else
      echo "tailscaled is not running"
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/tailscaled {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
EOF